dependencies:
  - name: cp-helm-charts
    version: 0.3.1
    repository: https://humio.github.io/cp-helm-charts
    import-values:
      - child: cp-zookeeper
        parent: zookeeper
      - child: cp-kafka
        parent: kafka
